name: Generate BC Building Code Artifact

on:
  workflow_dispatch: {}

jobs:
  build:
    # Allow run only when the workflow is dispatched from the specific branch
    if: ${{ github.ref == 'refs/heads/feature/IC2026-19_syncrepo2repo' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run transformation pipeline
        run: bash ../scripts/run-pipeline.sh


      - name: Upload combined artifact
        uses: actions/upload-artifact@v4
        with:
          name: bc-building-code-artifact
          path: |
            json-generation-pipeline/output/**
            bc-graphics/**
            graphics/**
